name: Continuous Integration

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    permissions: write-all
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v4
        with:
          node-version: 18.19.0
          cache: npm

      - name: Install Dependencies
        id: npm-ci
        run: npm ci

      - name: Lint
        id: npm-lint
        run: npm run lint

      - name: Intstall vsce dependency
        id: npm-vsce
        run: npm install -g @vscode/vsce@2.22.0

      - name: Generate Extension File
        id: generate-vsix
        run: vsce package

      - name: Set current artifaxt version as env variable
        run: echo "artifact_version=$(cat package.json | jq --raw-output '.version')" >> $GITHUB_ENV

      - name: Create Release
        id: create-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create "${env.artifact_version}" \
              --repo="$GITHUB_REPOSITORY" \
              --title="${GITHUB_REPOSITORY#*/} ${env.artifact_version}" \
              --generate-notes

      - name: Upload Relase Asset
        id: upload-release-asset
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload frc-*.vsix
              --repo="$GITHUB_REPOSITORY" \
